// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuTFsaoLMpvLgk_vH6UoIdwm5gPTzd2Uk',
    appId: '1:81331791443:web:7fa3663f736368a7c908a6',
    messagingSenderId: '81331791443',
    projectId: 'nsbmez',
    authDomain: 'nsbmez.firebaseapp.com',
    storageBucket: 'nsbmez.appspot.com',
    measurementId: 'G-HKXZ5WER8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQssJM7OZjnWoARUzqMJtnQzoU3ODtnFg',
    appId: '1:81331791443:android:3a958bb3601fbc5dc908a6',
    messagingSenderId: '81331791443',
    projectId: 'nsbmez',
    storageBucket: 'nsbmez.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6wJl7ShuzUJsoYYkh5cZNYZoFryyozGE',
    appId: '1:81331791443:ios:b8ef2292b9f50af0c908a6',
    messagingSenderId: '81331791443',
    projectId: 'nsbmez',
    storageBucket: 'nsbmez.appspot.com',
    iosClientId: '81331791443-s56trc0nmfdcn0k75e8vo55d5db3qeor.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6wJl7ShuzUJsoYYkh5cZNYZoFryyozGE',
    appId: '1:81331791443:ios:19d5ca01c630e445c908a6',
    messagingSenderId: '81331791443',
    projectId: 'nsbmez',
    storageBucket: 'nsbmez.appspot.com',
    iosClientId: '81331791443-obuhkk7tk11re30l7id1m8id042599vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication.RunnerTests',
  );
}
